### ISSUE TITLE
blogging analysis paralysis: hakyll, hugo

### ISSUE THREAD

**Issue by dckc** [dckc/madmode-blog#14]
I'm kinda scared of my python site builder now.

inspired by nix, I tried hakyll. The demo site was fine, but I got "cannot find $date$" for my 1st entry. And it stopped there; didn't even try to render any other pages. I thought about writing some haskell to update the page metadata, but... well... I miss tracebacks.

Plus ./site is ~47MB.

Next: giving hugo another try.

**Comment by dckc** [comment]
stackedit... interesting

[TheoryOfGraphs](https://stackedit.io/editor#!provider=couchdb&id=UdUSSGCZgNDxSIPYmMfoX5Kk)

[StackEdit. eval](https://gist.github.com/dckc/0057a3bf52c339e6249eb4860fd8f13b)

**Comment by dckc** [comment]
https://www.gatsbyjs.org/

**Comment by dckc** [comment]
3 tier https://www.aaron-gustafson.com/notebook/enabling-webmentions-in-jekyll/ 18 November 2014 #indieweb

**Comment by dckc** [comment]
## rust cap-std is a small neighborhood

> ... I'm interested to port it [[Zola](https://www.getzola.org/)] to [cap-std](https://github.com/bytecodealliance/cap-std).

The Zola sources seemed like a manageable size, but of course they're the tip of an iceberg; underneath this one line...

https://github.com/getzola/zola/blob/2e17c776605621cea7673e442577d520113efca7/components/libs/Cargo.toml#L45

... is the whole [walkdir crate](https://crates.io/crates/walkdir)

**Comment by dckc** [comment]
somewhat tempting...

 - [Ghost on the JAMstack \| Netlify](https://www.netlify.com/blog/2019/01/11/ghost-on-the-jamstack/)

**Comment by dckc** [comment]
I kicked the tires...

```
~/gatsby-starter-ghost
18:25 connolly@bldbox$ git remote -v
origin	https://github.com/TryGhost/gatsby-starter-ghost.git (fetch)
origin	https://github.com/TryGhost/gatsby-starter-ghost.git (push)
~/gatsby-starter-ghost
18:25 connolly@bldbox$ git log10 -n 2
2025-05-14 04:26 6894392 Update dependency @tryghost/helpers-gatsby to v2.0.24 (#707)
2025-05-14 00:55 9e8a564 Update dependency @tryghost/helpers to v1.1.93 (#706)
```

but then I looked for a "make a new item" button and instead found a ghost config file with an API key.

Would I use the normal hosted ghost service?
Where's the version control for the content? Can I give that up?

**Comment by dckc** [comment]
## local build fails

Pagefind (for #205) works by first building the site. But it failed due to a `cssmin` dependency problem.

`pipenv install cssmin` made the symptoms go away.

<details><summary>site build</summary>

```console
$ ./site build
Building website...
[2025-08-09 11:18:10,837] ERROR in app: Exception on /contact/ [GET]
Traceback (most recent call last):
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/webassets/filter/cssmin.py", line 19, in setup
    import cssmin
ModuleNotFoundError: No module named 'cssmin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/connolly/projects/madmode-blog/./site", line 183, in contact
    return render_template('contact.html')
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/connolly/projects/madmode-blog/templates/contact.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/connolly/projects/madmode-blog/templates/base.html", line 19, in top-level template code
    {%- assets filters="cssmin", output="packed.css",
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/webassets/ext/jinja2.py", line 187, in _render_assets
    urls = bundle.urls(calculate_sri=True)
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/webassets/bundle.py", line 833, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/webassets/bundle.py", line 767, in _urls
    self._build(ctx, extra_filters=extra_filters, force=False,
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/webassets/bundle.py", line 618, in _build
    hunk = self._merge_and_apply(
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/webassets/bundle.py", line 460, in _merge_and_apply
    filter.setup()
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/webassets/filter/cssmin.py", line 21, in setup
    raise EnvironmentError('The "cssmin" package is not installed.')
OSError: The "cssmin" package is not installed.
Traceback (most recent call last):
  File "/home/connolly/projects/madmode-blog/./site", line 382, in <module>
    parser.dispatch()
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/connolly/projects/madmode-blog/./site", line 281, in build
    freezer.freeze()
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/flask_frozen/__init__.py", line 205, in freeze
    return set(page.url for page in self.freeze_yield())
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/flask_frozen/__init__.py", line 205, in <genexpr>
    return set(page.url for page in self.freeze_yield())
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/flask_frozen/__init__.py", line 189, in freeze_yield
    new_filename = self._build_one(url, last_modified)
  File "/home/connolly/.local/share/virtualenvs/madmode-blog-1UB6vfSQ/lib/python3.10/site-packages/flask_frozen/__init__.py", line 337, in _build_one
    raise ValueError('Unexpected status %r on URL %s' \
ValueError: Unexpected status '500 INTERNAL SERVER ERROR' on URL /contact/
```

</details>

**Comment by dckc** [comment]
## Tab dump on writing workflows, the frustrations, and what's actually working

[MadMode: writing](https://www.madmode.com/search/label/writing/)

[MadMode: My Capability Security 2017 Wish-List | Home](https://www.madmode.com/2017/ocap-wish-list)

[Dan Connolly: "Electric cars are kinda cool, …" - social.coop](https://social.coop/@dckc/116671570186967948)

[advent of ocaps for AI · Issue #64 · dckc/awesome-ocap](https://github.com/dckc/awesome-ocap/issues/64#issuecomment-3605214021)

[Issues · dckc/madmode-blog](https://github.com/dckc/madmode-blog/issues?q=is%3Aissue%20state%3Aopen%20sort%3Aupdated-desc)

[diigo unreliable - migrate to Zotero? Hypothesis? · Issue #32 · dckc/madmode-blog](https://github.com/dckc/madmode-blog/issues/32)

[Improve Diigo backup reliability and port to Python 3 by dckc · Pull Request #242 · dckc/madmode-blog](https://github.com/dckc/madmode-blog/pull/242)

[Aaron Swartz's A Programmable Web: An Unfinished Work | Search Results | My Library | Zotero](https://www.zotero.org/connolly/search/unfinished/titleCreatorYear/items/P7NIURXA/item-list)

[Aaron Swartz  A Programmable Web.pdf](https://dn760001.eu.archive.org/0/items/AaronSwartzAProgrammableWeb/Aaron%20Swartz%20%20A%20Programmable%20Web.pdf)

[Tab Copy](https://tabcopy.com/)

[MadMode: Secure Mashups: CSRF\-resistent alternatives to WebID \| Home](https://www.madmode.com/2011/07/secure-mashups-csrf-resistent.html)

 - emacs magit
 - github
 - netlify
